src_first_django/first_django/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path

from teachers import views as teachers_views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('teachers/', include('teachers.urls')),
    path('groups/', include('groups.urls')),
    path('students/', include('students1.urls')),

    path('', teachers_views.index, name='index'),

    path(r'^silk/', include('silk.urls', namespace='silk')),
]

src_first_django/groups/urls.py
from django.urls import path

from groups import views

app_name = "groups"

urlpatterns = [
    path('show/', views.show_groups, name='show'),
    path('create/', views.create_group, name='create'),
    path('edit/<int:pk>', views.edit_group, name='edit'),
]

src_first_django/students1/urls.py
from django.urls import path

from students1 import views

app_name = "students"

urlpatterns = [
    path('generate_student/', views.generate_student, name='generate1'),
    path('generate_students/', views.generate_students, name='generate_many'),
    path('show/', views.show_students, name='show'),
    path('create/', views.create_student, name='create'),
    path('edit/<int:pk>/', views.edit_student, name='edit'),
]

src_first_django/teachers/urls.py
from django.urls import path

from teachers import views

app_name = "teachers"

urlpatterns = [
    path('show_filtered/', views.show_filtered_teachers, name='show_filtered'),
    path('generate/', views.generate_teachers, name='generate'),
    path('create/', views.create_teacher, name='create'),
    path('edit/<int:pk>', views.edit_teacher, name='edit'),
    path('show-logs', views.show_logs, name='show_logs'),
]

src_first_django/teachers/models.py
from django.db import models


class Teacher(models.Model):
    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    stupen = models.CharField(max_length=64)
    isCurator = models.BooleanField

    @property
    def full_name(self):
        return f'{self.stupen} {self.first_name} {self.last_name} '


class Logger(models.Model):
    method = models.CharField(max_length=256, default='')
    path = models.CharField(max_length=256, default='')
    execution_time = models.FloatField()
    created = models.CharField(max_length=256, default='')

    def info(self):
        return f'{self.method} | {self.path} | {self.execution_time}sec | {self.created}'

    def __str__(self):
        return self.info()

src_first_django/teachers/forms.py
from django import forms

from teachers.models import Teacher


class TeacherCreateForm(forms.ModelForm):

    class Meta:
        model = Teacher
        fields = ("first_name", "last_name", "stupen")

src_first_django/teachers/views.py
import random

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt

from faker import Faker

from teachers.forms import TeacherCreateForm
from teachers.models import Logger, Teacher


fake = Faker("uk_UA")
stups = ['professor', 'docent', 'assistant']


def make_fake_teacher() -> Teacher:
    return Teacher(first_name=fake.first_name(), last_name=fake.last_name(), stupen=random.choice(stups))


def generate_teachers(request):
    teach = []
    count = request.GET.get('count', 20)
    response = "Teachers have been generated"
    if count.isdigit() and 0 < int(count) <= 120:
        for _ in range(int(count) + 1):
            teach.append(make_fake_teacher())
        Teacher.objects.bulk_create(teach)
    else:
        response = "Invalid parameter"
    return HttpResponse(response)


def show_filtered_teachers(request):
    response = ""
    teach = Teacher.objects.all()
    fn = request.GET.get('first_name', None)
    ln = request.GET.get('last_name', None)
    if fn is not None:
        teach = Teacher.objects.filter(first_name=fn)
    if ln is not None:
        teach = Teacher.objects.filter(last_name=ln)
    teach = list(teach)
    for obj in teach:
        response += f'{obj.full_name}</br>'
    return render(request, 'show-teachers.html', context={'teachers': teach})


def index(request):
    return render(request, 'index.html')


@csrf_exempt
def create_teacher(request):
    if request.method == "POST":
        form = TeacherCreateForm(request.POST)

        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('teachers:show_filtered'))

    elif request.method == "GET":
        form = TeacherCreateForm()

    return render(request, 'create-student.html', context={'form': form})


@csrf_exempt
def edit_teacher(request, pk):

    teach = get_object_or_404(Teacher, id=pk)

    if request.method == "POST":
        form = TeacherCreateForm(request.POST, instance=teach)

        if 'delete' in request.POST:
            teach.delete()
            return HttpResponseRedirect(reverse('teachers:show_filtered'))

        elif 'submit' in request.POST:
            if form.is_valid():
                form.save()
                return HttpResponseRedirect(reverse('teachers:show_filtered'))

    elif request.method == "GET":
        form = TeacherCreateForm(instance=teach)

    return render(request, 'edit-teacher.html', context={'form': form})


def show_logs(request):
    response = ""
    logs = Logger.objects.all().iterator()
    for log in logs:
        response += log.info()+'<br>'
    return HttpResponse(response)

src_first_django/teachers/templates/create-teacher.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>


<p>Hier kann man einen Lehrer schaffen</p>
<form>
    {{ create_form.as_p }}
    <button type="Submit">Submit</button>
</form>

</body>
</html>

src_first_django/teachers/templates/edit-teacher.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>


<p>Edit teacher</p>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="Submit" name="submit">Submit</button><br>
    <button type="Submit" name="delete">Delete</button><br>
</form>

</body>
</html>

src_first_django/teachers/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
</head>
<body>

<a href="{% url 'students:create' %}">create student</a><br>
<a href="{% url 'students:show' %}">show all students</a><br>
<hr>
<a href="{% url 'teachers:create' %}">create teacher</a><br>
<a href="{% url 'teachers:show_filtered' %}">show all teachers</a><br>
<hr>
<a href="{% url 'groups:create' %}">create group</a><br>
<a href="{% url 'groups:show' %}">show all groups</a><br>
<hr>
<a href="{% url 'teachers:show_logs' %}">show admin logs</a><br>

</body>
</html>

src_first_django/teachers/templates/show-teachers.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<a href = "{% url 'index' %}">Back to index</a>
<hr>
List of teachers<br>
<hr>
{% for t in teachers %}
    {{ t.id }} {{ t.full_name }}<a href="{% url 'teachers:edit' t.id %}">EDIT</a><br>
{% endfor %}


</body>
</html>