src_first_django/first_django/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path

from teachers import views as teachers_views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('teachers/', include('teachers.urls')),
    path('groups/', include('groups.urls')),
    path('students/', include('students1.urls')),

    path('', teachers_views.index, name='index'),

    path(r'^silk/', include('silk.urls', namespace='silk')),
]

src_first_django/groups/urls.py
from django.urls import path

from groups import views

app_name = "groups"

urlpatterns = [
    path('show/', views.show_groups, name='show'),
    path('create/', views.create_group, name='create'),
    path('edit/<int:pk>', views.edit_group, name='edit'),
]

src_first_django/groups/models.py
from django.db import models


# Create your models here.
class Group(models.Model):
    facult = models.CharField(max_length=64)
    spec = models.CharField(max_length=64)
    year = models.PositiveSmallIntegerField(max_length=64)
    number_of_students = models.PositiveSmallIntegerField(max_length=64)

    @property
    def code_of_group(self):
        return f'{str(self.facult)[0]}{str(self.spec)[0]}-{self.year}'

    def __str__(self):
        return f'{str(self.facult)} {str(self.spec)} {self.year}'

src_first_django/groups/forms.py
from django import forms

from groups.models import Group


class GroupCreateForm(forms.ModelForm):

    class Meta:
        model = Group
        fields = ("facult", "spec", "year", "number_of_students")

src_first_django/groups/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt


from groups.forms import GroupCreateForm
from groups.models import Group


@csrf_exempt
def create_group(request):
    if request.method == "POST":
        form = GroupCreateForm(request.POST)

        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('groups:show'))

    elif request.method == "GET":
        form = GroupCreateForm()

    return render(request, 'create-student.html', context={'form': form})


def show_groups(request):
    response = ""
    gr = list(Group.objects.all())
    for group in gr:
        response += f'{group.code_of_group}</br>'
    return render(request, 'show-groups.html', context={'groups': gr})


@csrf_exempt
def edit_group(request, pk):

    gr = get_object_or_404(Group, id=pk)

    if request.method == "POST":
        form = GroupCreateForm(request.POST, instance=gr)

        if 'delete' in request.POST:
            gr.delete()
            return HttpResponseRedirect(reverse('groups:show'))

        elif 'submit' in request.POST:
            if form.is_valid():
                form.save()
                return HttpResponseRedirect(reverse('groups:show'))

    elif request.method == "GET":
        form = GroupCreateForm(instance=gr)

    return render(request, 'edit-group.html', context={'form': form})

src_first_django/groups/templates/create_group.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>


<p>Create new Group</p>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="Submit">Submit</button>
</form>

</body>
</html>

src_first_django/groups/templates/edit-group.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<p>Edit group</p>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="Submit" name="submit">Submit</button><br>
    <button type="Submit" name="delete">Delete</button><br>
</form>


</body>
</html>

src_first_django/groups/templates/show-groups.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<a href = "{% url 'index' %}">Back to index</a>
<hr>
List of groups<br>
<hr>
{% for g in groups %}
    {{ g.id }} {{ g.code_of_group }} <a href="{% url 'groups:edit' g.id %}">EDIT</a><br>
{% endfor %}
</body>
</html>